package com.liutf.mvc.entity.mysql;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 用户余额实体
 *
 * @author ltf
 * @create 2018-11-10 上午 12:27
 */
public class CustomerBalance {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.customer_id
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private Long customerId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.account
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private BigDecimal account;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.account_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private BigDecimal accountWithdrawal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.account_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private BigDecimal accountWithdrawalUnable;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.freeze_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private BigDecimal freezeWithdrawal;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.freeze_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private BigDecimal freezeWithdrawalUnable;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.create_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column customer_balance.lost_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    private Date lostTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.customer_id
     * @return  the value of customer_balance.customer_id
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.customer_id
     * @param customerId  the value for customer_balance.customer_id
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.account
     * @return  the value of customer_balance.account
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public BigDecimal getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.account
     * @param account  the value for customer_balance.account
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setAccount(BigDecimal account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.account_withdrawal
     * @return  the value of customer_balance.account_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public BigDecimal getAccountWithdrawal() {
        return accountWithdrawal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.account_withdrawal
     * @param accountWithdrawal  the value for customer_balance.account_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setAccountWithdrawal(BigDecimal accountWithdrawal) {
        this.accountWithdrawal = accountWithdrawal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.account_withdrawal_unable
     * @return  the value of customer_balance.account_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public BigDecimal getAccountWithdrawalUnable() {
        return accountWithdrawalUnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.account_withdrawal_unable
     * @param accountWithdrawalUnable  the value for customer_balance.account_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setAccountWithdrawalUnable(BigDecimal accountWithdrawalUnable) {
        this.accountWithdrawalUnable = accountWithdrawalUnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.freeze_withdrawal
     * @return  the value of customer_balance.freeze_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public BigDecimal getFreezeWithdrawal() {
        return freezeWithdrawal;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.freeze_withdrawal
     * @param freezeWithdrawal  the value for customer_balance.freeze_withdrawal
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setFreezeWithdrawal(BigDecimal freezeWithdrawal) {
        this.freezeWithdrawal = freezeWithdrawal;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.freeze_withdrawal_unable
     * @return  the value of customer_balance.freeze_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public BigDecimal getFreezeWithdrawalUnable() {
        return freezeWithdrawalUnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.freeze_withdrawal_unable
     * @param freezeWithdrawalUnable  the value for customer_balance.freeze_withdrawal_unable
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setFreezeWithdrawalUnable(BigDecimal freezeWithdrawalUnable) {
        this.freezeWithdrawalUnable = freezeWithdrawalUnable;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.create_time
     * @return  the value of customer_balance.create_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.create_time
     * @param createTime  the value for customer_balance.create_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column customer_balance.lost_time
     * @return  the value of customer_balance.lost_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public Date getLostTime() {
        return lostTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column customer_balance.lost_time
     * @param lostTime  the value for customer_balance.lost_time
     * @mbggenerated  Fri Aug 18 21:24:32 CST 2017
     */
    public void setLostTime(Date lostTime) {
        this.lostTime = lostTime;
    }

}
