package com.liutf.mvc.entity.mysql;

import java.io.Serializable;
import java.util.Date;

/**
 * 用户等级
 *
 * @author ltf
 * @create 2018-11-09 下午 11:48
 */
public class CustomerLevelPoint  implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.customer_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.level_point
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Integer levelPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.level_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.level_name
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.create_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_level_point.level_update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    private Date levelUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.customer_id
     *
     * @return the value of customer_level_point.customer_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.customer_id
     *
     * @param customerId the value for customer_level_point.customer_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.level_point
     *
     * @return the value of customer_level_point.level_point
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Integer getLevelPoint() {
        return levelPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.level_point
     *
     * @param levelPoint the value for customer_level_point.level_point
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setLevelPoint(Integer levelPoint) {
        this.levelPoint = levelPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.level_id
     *
     * @return the value of customer_level_point.level_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.level_id
     *
     * @param levelId the value for customer_level_point.level_id
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.level_name
     *
     * @return the value of customer_level_point.level_name
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.level_name
     *
     * @param levelName the value for customer_level_point.level_name
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.create_time
     *
     * @return the value of customer_level_point.create_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.create_time
     *
     * @param createTime the value for customer_level_point.create_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.update_time
     *
     * @return the value of customer_level_point.update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.update_time
     *
     * @param updateTime the value for customer_level_point.update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_level_point.level_update_time
     *
     * @return the value of customer_level_point.level_update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public Date getLevelUpdateTime() {
        return levelUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_level_point.level_update_time
     *
     * @param levelUpdateTime the value for customer_level_point.level_update_time
     *
     * @mbg.generated Mon Aug 07 15:24:24 CST 2017
     */
    public void setLevelUpdateTime(Date levelUpdateTime) {
        this.levelUpdateTime = levelUpdateTime;
    }

}
